name: quickfix2
description: QuickFix – szybkie zlecenia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1  # TYLKO TO
  cloud_firestore: ^5.4.4
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  uuid: ^4.5.1
  firebase_messaging: ^15.1.3
  cupertino_icons: ^1.0.8
  google_maps_flutter_web: ^0.5.14+2  # DODANE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


# pubspec.yaml
firebase_messaging: ^15.1.3