# ios/Podfile
platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter pods
  pod 'Flutter', :path => File.dirname(__FILE__).to_s + '/Flutter'

  # Dodaj wszystkie pluginy Flutter
  flutter_application_path = File.expand_path('..', __FILE__)
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end